name: Record ATIS Audio

on:
  schedule:
    - cron: '22,52 * * * *'
  workflow_dispatch:

jobs:
  record:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Record and Filter Audio (2m30s)
        run: |
          # Enregistrement avec filtrage audio :
          # highpass=f=200 : supprime les bourdonnements graves
          # lowpass=f=3500 : supprime le souffle aigu des radios
          # afftdn=nr=15 : réduction de bruit adaptative
          ffmpeg -y -i "https://icecast.kobly.com/eetn2_atis" -t 150 \
          -af "highpass=f=200, lowpass=f=3500, afftdn=nr=15:nt=w" \
          -c:a pcm_s16le -ar 16000 -ac 1 atis_recorded.wav

      - name: Verify Audio
        run: ls -lh atis_recorded.wav

      - name: Commit and Push Audio
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add atis_recorded.wav
          # Le || exit 0 évite une erreur si aucun changement n'est détecté
          git commit -m "New Audio Recording: $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push
